require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.4'
install! 'cocoapods', :deterministic_uuids => false

production = ENV["PRODUCTION"] == "1"

# dynamic_frameworks = ['libWantToUseUserFramework']
target 'HelloWorld' do
  config = use_native_modules!
  pod 'IQKeyboardManagerSwift'
  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :production => production,
    :hermes_enabled => true,
    :fabric_enabled => flags[:fabric_enabled],
    :flipper_configuration => FlipperConfiguration.enabled,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'HelloWorldTests' do
    inherit! :complete
    # Pods for testing
  end

  # If u want to enable use_frameworks for one or more library.
  # unconment below and dynamic_frameworks (Line 5)
  # pre_install do |installer|
  #   installer.pod_targets.each do |pod|
  #     if dynamic_frameworks.include?(pod.name)
  #       puts "Overriding the dynamic_framework? method for #{pod.name}"
  #       def pod.dynamic_framework?;
  #         true
  #       end
  #       def pod.build_type;
  #         Pod::BuildType.dynamic_framework
  #       end
  #     end
  #   end
  # end
  
  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
