// This file was generated by current env while u run application.
// Do not edit this file as changes may cause incorrect behavior and will be lost
// once the code is regenerated.

import Config from 'react-native-config';

export const APP_BUILD_VERSION = '1.0.0.2023.01.01.01.01';

export const {
  API_URL,
  APP_DISPLAY_NAME,
  VERSION_CODE,
  VERSION_NAME,
  BUNDLE_IDENTIFIER,
  DEFAULT_FALLBACK_LNG_I18n,
  PRIVATE_KEY_STORAGE,
  WORKSPACE_NAME,
  SCHEME_SUFFIX,
  SPLASH_STORYBOARD_NAME,
  ASSETCATALOG_COMPILER_APPICON_NAME,
  DEBUG_PROVISIONING_PROFILE,
  RELEASE_PROVISIONING_PROFILE,
  PUBLISH_PROVISIONING_PROFILE,
  APPLE_DEVELOPMENT_TEAM,
  FLAVOR,
  ANDROID_KEY_STORE_FILE,
  ANDROID_KEY_STORE_PASSWORD,
  ANDROID_KEY_STORE_KEY_ALIAS,
  ANDROID_KEY_STORE_KEY_PASSWORD,
} = Config as Record<string, string>;