// This file was generated by current env while u run application.
// Do not edit this file as changes may cause incorrect behavior and will be lost
// once the code is regenerated.

import Keys from 'react-native-keys';

export const APP_BUILD_VERSION = '1.0.0.2024.01.01.23.13';

export const { DEFAULT_FALLBACK_LNG_I18n } = Keys;

export const { BUNDLE_IDENTIFIER } = Keys;

export const { VERSION_NAME } = Keys;

export const { VERSION_CODE } = Keys;

export const { API_URL } = Keys;

export const { APP_DISPLAY_NAME } = Keys;

export const { WORKSPACE_NAME } = Keys;

export const { SCHEME_SUFFIX } = Keys;

export const { SPLASH_STORYBOARD_NAME } = Keys;

export const { ASSETCATALOG_COMPILER_APPICON_NAME } = Keys;

export const { DEBUG_PROVISIONING_PROFILE } = Keys;

export const { RELEASE_PROVISIONING_PROFILE } = Keys;

export const { PUBLISH_PROVISIONING_PROFILE } = Keys;

export const { APPLE_DEVELOPMENT_TEAM } = Keys;

export const { FLAVOR } = Keys;

export const PRIVATE_KEY_STORAGE = Keys.secureFor('PRIVATE_KEY_STORAGE');
