#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

yarn lint
# yarn lint-staged

AUTHORS=(
  'helloworld:helloworld@gmail.com'
)

# AUTHOR_CONFIG="$GIT_AUTHOR_NAME:$GIT_AUTHOR_EMAIL"

# if [[ ! " ${AUTHORS[*]} " =~ " ${AUTHOR_CONFIG} " ]]; then
#   echo ⛔️🚫⛔️🚫⛔️🚫⛔️🚫⛔️🚫⛔️🚫⛔️🚫⛔️🚫⛔️🚫⛔️🚫⛔️🚫⛔️🚫⛔️🚫
#   echo "Your name should be the same as your username."
#   echo "Example: helloworld <helloworld@gmail.com>"
#   echo
#   echo "Fix your username by using:"
#   echo "git config user.name helloworld"
#   echo "git config user.email helloworld@gmail.com"
#   echo "Then try commiting again"
#   echo ⛔️🚫⛔️🚫⛔️🚫⛔️🚫⛔️🚫⛔️🚫⛔️🚫⛔️🚫⛔️🚫⛔️🚫⛔️🚫⛔️🚫⛔️🚫
#   exit 1
# fi