const DEFAULT_ITEM_HEIGHT: number = 50;
const DEFAULT_WRAPPER_HEIGHT: number = 250;
const DEFAULT_HIGHT_LIGHT_LINE_COLOR: string = 'gray';
const DEFAULT_PLACE_HOLDER_COLOR: string = 'rgba(255,255,255,.7)';

export {
    DEFAULT_ITEM_HEIGHT,
    DEFAULT_WRAPPER_HEIGHT,
    DEFAULT_HIGHT_LIGHT_LINE_COLOR,
    DEFAULT_PLACE_HOLDER_COLOR
}