
// Cover size
const BASE_LINE_COVER_SIZE = 48;
const BASE_LINE_FORCE_GROUND_COVER_SIZE = 108;

// Left and Top position of icon in cover
const PADDING_FORCE_GROUND_BASE_LINE = 18;
const PADDING_CIRCLE_BASE_LINE = 2;
const PADDING_SQUARE_BASE_LINE = 4;

// Icon size
const BASE_LINE_FORCE_GROUND_ICON_SIZE = BASE_LINE_FORCE_GROUND_COVER_SIZE - (PADDING_FORCE_GROUND_BASE_LINE * 2);

const BASE_LINE_SQUARE_ICON_SIZE = BASE_LINE_COVER_SIZE - (PADDING_SQUARE_BASE_LINE * 2);
const BASE_LINE_SQUARE_ICON_RADIUS = BASE_LINE_SQUARE_ICON_SIZE * 0.0833;

const BASE_LINE_CIRCLE_ICON_SIZE = BASE_LINE_COVER_SIZE - (PADDING_CIRCLE_BASE_LINE * 2);
const BASE_LINE_CIRCLE_ICON_RADIUS = BASE_LINE_CIRCLE_ICON_SIZE / 2;

const HDPI_RATIO = 1.5;
const XHDPI_RATIO = 2;
const XXHDPI_RATIO = 3;
const XXXHDPI_RATIO = 4;

const iconSourceSet = {
    'mipmap-mdpi':{
        forceGroundCoverSize:BASE_LINE_FORCE_GROUND_COVER_SIZE,
        forceGroundIconSize:BASE_LINE_FORCE_GROUND_ICON_SIZE,
        paddingForceGround:PADDING_FORCE_GROUND_BASE_LINE,

        coverSize:BASE_LINE_COVER_SIZE,

        iconSquareSize:BASE_LINE_SQUARE_ICON_SIZE,
        iconSquareRadius:BASE_LINE_SQUARE_ICON_RADIUS,
        paddingSquare:PADDING_SQUARE_BASE_LINE,

        iconCircleSize:BASE_LINE_CIRCLE_ICON_SIZE,
        iconCircleRadius:BASE_LINE_CIRCLE_ICON_RADIUS,
        paddingCircle:PADDING_CIRCLE_BASE_LINE ,
    },
    'mipmap-hdpi':{
        forceGroundCoverSize:BASE_LINE_FORCE_GROUND_COVER_SIZE * HDPI_RATIO,
        forceGroundIconSize:BASE_LINE_FORCE_GROUND_ICON_SIZE * HDPI_RATIO,
        paddingForceGround:PADDING_FORCE_GROUND_BASE_LINE * HDPI_RATIO,

        coverSize:BASE_LINE_COVER_SIZE * HDPI_RATIO,

        iconSquareSize:BASE_LINE_SQUARE_ICON_SIZE * HDPI_RATIO,
        iconSquareRadius:BASE_LINE_SQUARE_ICON_RADIUS * HDPI_RATIO,
        paddingSquare:PADDING_SQUARE_BASE_LINE * HDPI_RATIO,

        iconCircleSize:BASE_LINE_CIRCLE_ICON_SIZE * HDPI_RATIO,
        iconCircleRadius:BASE_LINE_CIRCLE_ICON_RADIUS * HDPI_RATIO,
        paddingCircle:PADDING_CIRCLE_BASE_LINE * HDPI_RATIO,

    },
    'mipmap-xhdpi':{
        forceGroundCoverSize:BASE_LINE_FORCE_GROUND_COVER_SIZE * XHDPI_RATIO,
        forceGroundIconSize:BASE_LINE_FORCE_GROUND_ICON_SIZE * XHDPI_RATIO,
        paddingForceGround:PADDING_FORCE_GROUND_BASE_LINE * XHDPI_RATIO,

        coverSize:BASE_LINE_COVER_SIZE * XHDPI_RATIO,

        iconSquareSize:BASE_LINE_SQUARE_ICON_SIZE * XHDPI_RATIO,
        iconSquareRadius:BASE_LINE_SQUARE_ICON_RADIUS * XHDPI_RATIO,
        paddingSquare:PADDING_SQUARE_BASE_LINE * XHDPI_RATIO,

        iconCircleSize:BASE_LINE_CIRCLE_ICON_SIZE * XHDPI_RATIO,
        iconCircleRadius:BASE_LINE_CIRCLE_ICON_RADIUS * XHDPI_RATIO,
        paddingCircle:PADDING_CIRCLE_BASE_LINE * XHDPI_RATIO,
    },
    'mipmap-xxhdpi':{
        forceGroundCoverSize:BASE_LINE_FORCE_GROUND_COVER_SIZE * XXHDPI_RATIO,
        forceGroundIconSize:BASE_LINE_FORCE_GROUND_ICON_SIZE * XXHDPI_RATIO,
        paddingForceGround:PADDING_FORCE_GROUND_BASE_LINE * XXHDPI_RATIO,

        coverSize:BASE_LINE_COVER_SIZE * XXHDPI_RATIO,

        iconSquareSize:BASE_LINE_SQUARE_ICON_SIZE * XXHDPI_RATIO,
        iconSquareRadius:BASE_LINE_SQUARE_ICON_RADIUS * XXHDPI_RATIO,
        paddingSquare:PADDING_SQUARE_BASE_LINE * XXHDPI_RATIO,

        iconCircleSize:BASE_LINE_CIRCLE_ICON_SIZE * XXHDPI_RATIO,
        iconCircleRadius:BASE_LINE_CIRCLE_ICON_RADIUS * XXHDPI_RATIO,
        paddingCircle:PADDING_CIRCLE_BASE_LINE * XXHDPI_RATIO,
    },
    'mipmap-xxxhdpi':{
        forceGroundCoverSize:BASE_LINE_FORCE_GROUND_COVER_SIZE * XXXHDPI_RATIO,
        forceGroundIconSize:BASE_LINE_FORCE_GROUND_ICON_SIZE * XXXHDPI_RATIO,
        paddingForceGround:PADDING_FORCE_GROUND_BASE_LINE * XXXHDPI_RATIO,

        coverSize:BASE_LINE_COVER_SIZE * XXXHDPI_RATIO,

        iconSquareSize:BASE_LINE_SQUARE_ICON_SIZE * XXXHDPI_RATIO,
        iconSquareRadius:BASE_LINE_SQUARE_ICON_RADIUS * XXXHDPI_RATIO,
        paddingSquare:PADDING_SQUARE_BASE_LINE * XXXHDPI_RATIO,

        iconCircleSize:BASE_LINE_CIRCLE_ICON_SIZE * XXXHDPI_RATIO,
        iconCircleRadius:BASE_LINE_CIRCLE_ICON_RADIUS * XXXHDPI_RATIO,
        paddingCircle:PADDING_CIRCLE_BASE_LINE * XXXHDPI_RATIO,
    },
};
module.exports = {iconSourceSet};
