export const SET_INTERNET_OFF = 'SET_INTERNET_OFF'
export const SET_INTERNET_ON = 'SET_INTERNET_ON'
export const SET_TOKEN = 'SET_TOKEN'
export const SET_APP_PROFILE = 'SET_APP_PROFILE'
export const LOG_OUT = 'LOG_OUT'
export const SET_APP_THEME = 'SET_APP_THEME'
export const SET_APP_MODE = 'SET_APP_MODE'