export const SET_INTERNET = 'SET_INTERNET'
export const SET_TOKEN = 'SET_TOKEN'
export const SET_APP_PROFILE = 'SET_APP_PROFILE'
export const LOG_OUT = 'LOG_OUT'
export const SET_APP_THEME = 'SET_APP_THEME'
export const SET_APP_MODE = 'SET_APP_MODE'